from __future__ import annotations

import hashlib
import json
import subprocess
from copy import deepcopy
from pathlib import Path

import pytest

from tools import obsidian_knowledge_sync as sync


def _write(path: Path, text: str = "# fixture\n") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _blob(text: str) -> str:
    data = text.encode("utf-8")
    header = f"blob {len(data)}\0".encode("ascii")
    return hashlib.sha1(header + data, usedforsecurity=False).hexdigest()


def _entry(path: str = "docs/doc.md") -> dict[str, object]:
    return {
        "path": path,
        "title": "Документ",
        "doc_type": "guide",
        "area": "project",
        "status": "active",
        "summary": "Проверочный документ.",
        "tags": ["область/project", "тип/guide", "статус/active"],
    }


def _registry(entries: list[dict[str, object]] | None = None) -> dict[str, object]:
    return {
        "schema": sync.SCHEMA,
        "schema_version": 1,
        "authority_scope": sync.AUTHORITY_SCOPE,
        "generation_direction": sync.GENERATION_DIRECTION,
        "entries": entries or [_entry()],
    }


def _baseline(blobs: dict[str, str] | None = None) -> dict[str, object]:
    return {
        "schema": sync.BASELINE_SCHEMA,
        "schema_version": 1,
        "baseline_commit": sync.BASELINE_COMMIT,
        "scope": ["AGENTS.md", "README.md", "README_RUS.md", "ROADMAP.md", "docs/**/*.md"],
        "exempt_prefixes": ["docs/development/research_radar/", "docs/research/obsidian/"],
        "exempt_paths": [sync.GENERATED_INDEX_PATH],
        "baseline_blobs": blobs or {},
    }


def _git_add_all(tmp_path: Path) -> None:
    if not (tmp_path / ".git").exists():
        subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)


def _prepare(
    tmp_path: Path,
    data: dict[str, object] | None = None,
    *,
    extra_baseline: dict[str, str] | None = None,
) -> tuple[Path, Path]:
    registry_data = data or _registry()
    baseline_blobs: dict[str, str] = dict(extra_baseline or {})
    for raw_entry in registry_data["entries"]:  # type: ignore[index]
        entry = raw_entry
        path = str(entry["path"])
        if ".." not in Path(path).parts and not path.startswith("/"):
            text = "# fixture\n"
            _write(tmp_path / path, text)
            if path.endswith(".md"):
                baseline_blobs.setdefault(path, _blob(text))
        for relation in sync.RELATION_KEYS:
            for target in entry.get(relation, []):  # type: ignore[union-attr]
                _write(tmp_path / str(target))

    registry_path = tmp_path / sync.DEFAULT_REGISTRY
    registry_path.parent.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(
        json.dumps(registry_data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    boundary_path = tmp_path / sync.DEFAULT_BASELINE
    boundary_path.write_text(
        json.dumps(_baseline(baseline_blobs), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    _git_add_all(tmp_path)
    return registry_path, tmp_path / sync.DEFAULT_OUTPUT


def test_write_then_check_roundtrip_materializes_all_views(tmp_path: Path) -> None:
    _, output_path = _prepare(tmp_path)

    assert sync.main(["--repo-root", str(tmp_path), "--write"]) == 0
    assert output_path.is_file()
    assert sync.main(["--repo-root", str(tmp_path), "--check"]) == 0

    expected = [
        sync.DEFAULT_OUTPUT,
        sync.DEFAULT_INVENTORY,
        sync.DEFAULT_HOME,
        sync.DEFAULT_ANALYTICS,
        sync.DEFAULT_KNOWLEDGE_BASE,
        sync.DEFAULT_RELATIONS_BASE,
        sync.DEFAULT_TERMS_BASE,
    ]
    for path in expected:
        assert (tmp_path / path).is_file(), path

    assert "GENERATED BY tools/obsidian_knowledge_sync.py" in output_path.read_text(encoding="utf-8")
    inventory = json.loads((tmp_path / sync.DEFAULT_INVENTORY).read_text(encoding="utf-8"))
    assert inventory["authority_scope"] == sync.INVENTORY_AUTHORITY
    assert inventory["source_fingerprint"]
    base_text = (tmp_path / sync.DEFAULT_KNOWLEDGE_BASE).read_text(encoding="utf-8")
    assert "filters:" in base_text
    assert "views:" in base_text
    assert "groupBy:" in base_text


def test_build_is_deterministic(tmp_path: Path) -> None:
    registry_path, _ = _prepare(tmp_path)
    boundary_path = tmp_path / sync.DEFAULT_BASELINE
    blobs = sync.tracked_worktree_blobs(tmp_path)
    _, entries_a, outputs_a, missing_a = sync.build_projections(
        tmp_path, registry_path, boundary_path, tracked_blobs=blobs
    )
    _, entries_b, outputs_b, missing_b = sync.build_projections(
        tmp_path, registry_path, boundary_path, tracked_blobs=blobs
    )
    assert entries_a == entries_b
    assert outputs_a == outputs_b
    assert missing_a == missing_b == []


def test_check_rejects_missing_projection(tmp_path: Path) -> None:
    _prepare(tmp_path)
    assert sync.main(["--repo-root", str(tmp_path), "--check"]) == 1


def test_check_rejects_stale_any_projection(tmp_path: Path) -> None:
    _prepare(tmp_path)
    assert sync.main(["--repo-root", str(tmp_path), "--write"]) == 0
    analytics = tmp_path / sync.DEFAULT_ANALYTICS
    analytics.write_text(analytics.read_text(encoding="utf-8") + "manual drift\n", encoding="utf-8")
    assert sync.main(["--repo-root", str(tmp_path), "--check"]) == 1


def test_new_human_markdown_requires_registration(tmp_path: Path) -> None:
    registry_path, _ = _prepare(tmp_path)
    new_path = tmp_path / "docs/new.md"
    _write(new_path, "# new\n")
    _git_add_all(tmp_path)

    with pytest.raises(sync.RegistryError, match="registration-required Markdown"):
        sync.build_projections(tmp_path, registry_path, tmp_path / sync.DEFAULT_BASELINE)


def test_changed_grandfathered_markdown_requires_registration(tmp_path: Path) -> None:
    old = "# old\n"
    registry_path, _ = _prepare(tmp_path, extra_baseline={"docs/old.md": _blob(old)})
    _write(tmp_path / "docs/old.md", old)
    _git_add_all(tmp_path)
    _write(tmp_path / "docs/old.md", "# changed\n")

    with pytest.raises(sync.RegistryError, match="docs/old.md"):
        sync.build_projections(tmp_path, registry_path, tmp_path / sync.DEFAULT_BASELINE)


def test_unchanged_grandfathered_markdown_may_remain_unregistered(tmp_path: Path) -> None:
    old = "# old\n"
    registry_path, _ = _prepare(tmp_path, extra_baseline={"docs/old.md": _blob(old)})
    _write(tmp_path / "docs/old.md", old)
    _git_add_all(tmp_path)

    _, _, outputs, missing = sync.build_projections(
        tmp_path, registry_path, tmp_path / sync.DEFAULT_BASELINE
    )
    assert missing == []
    inventory = json.loads(outputs[sync.DEFAULT_INVENTORY.as_posix()])
    row = next(item for item in inventory["entries"] if item["path"] == "docs/old.md")
    assert row["registration_state"] == "grandfathered"


def test_radar_generated_projection_remains_exempt_from_global_registration(tmp_path: Path) -> None:
    registry_path, _ = _prepare(tmp_path)
    _write(tmp_path / "docs/research/obsidian/TOPICS/topic__x.md", "# generated\n")
    _git_add_all(tmp_path)

    _, _, outputs, missing = sync.build_projections(
        tmp_path, registry_path, tmp_path / sync.DEFAULT_BASELINE
    )
    assert missing == []
    inventory = json.loads(outputs[sync.DEFAULT_INVENTORY.as_posix()])
    row = next(
        item
        for item in inventory["entries"]
        if item["path"] == "docs/research/obsidian/TOPICS/topic__x.md"
    )
    assert row["ownership_class"] == "generated_projection"
    assert row["registration_state"] == "exempt"


def test_source_fingerprint_changes_with_registered_document_blob(tmp_path: Path) -> None:
    registry_path, _ = _prepare(tmp_path)
    boundary_path = tmp_path / sync.DEFAULT_BASELINE
    _, _, outputs_before, _ = sync.build_projections(tmp_path, registry_path, boundary_path)
    before = json.loads(outputs_before[sync.DEFAULT_INVENTORY.as_posix()])["source_fingerprint"]

    _write(tmp_path / "docs/doc.md", "# changed registered document\n")
    _, _, outputs_after, _ = sync.build_projections(tmp_path, registry_path, boundary_path)
    after = json.loads(outputs_after[sync.DEFAULT_INVENTORY.as_posix()])["source_fingerprint"]
    assert after != before


def test_invalid_vocabulary_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["doc_type"] = "unknown"
    registry_path, _ = _prepare(tmp_path, _registry([entry]))
    with pytest.raises(sync.RegistryError, match="unsupported value"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_unapproved_tag_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["tags"] = ["область/project", "тип/guide", "статус/active", "random/tag"]
    registry_path, _ = _prepare(tmp_path, _registry([entry]))
    with pytest.raises(sync.RegistryError, match="controlled taxonomy mismatch"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_missing_path_is_rejected(tmp_path: Path) -> None:
    registry_path, _ = _prepare(tmp_path, _registry([_entry("docs/missing.md")]))
    (tmp_path / "docs/missing.md").unlink()
    with pytest.raises(sync.RegistryError, match="does not exist"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_duplicate_path_is_rejected(tmp_path: Path) -> None:
    first = _entry()
    second = deepcopy(first)
    second["title"] = "Дубликат"
    registry_path, _ = _prepare(tmp_path, _registry([first, second]))
    with pytest.raises(sync.RegistryError, match="duplicate registry path"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_path_traversal_is_rejected(tmp_path: Path) -> None:
    registry_path, _ = _prepare(tmp_path, _registry([_entry("../escape.md")]))
    with pytest.raises(sync.RegistryError, match="path traversal"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_empty_optional_list_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["terms"] = []
    registry_path, _ = _prepare(tmp_path, _registry([entry]))
    with pytest.raises(sync.RegistryError, match="non-empty list"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_missing_relation_target_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["related"] = ["docs/missing-target.md"]
    registry_path, _ = _prepare(tmp_path, _registry([entry]))
    (tmp_path / "docs/missing-target.md").unlink()
    with pytest.raises(sync.RegistryError, match="referenced file does not exist"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


@pytest.mark.parametrize("bad_target", ["docs/a\nb.md", "docs/a\rb.md"])
def test_multiline_relation_target_is_rejected(tmp_path: Path, bad_target: str) -> None:
    entry = _entry()
    entry["related"] = [bad_target]
    _write(tmp_path / "docs/doc.md")
    registry_path = tmp_path / sync.DEFAULT_REGISTRY
    registry_path.parent.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(
        json.dumps(_registry([entry]), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    with pytest.raises(sync.RegistryError, match="CR/LF forbidden"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_self_relation_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["related"] = ["docs/doc.md"]
    registry_path, _ = _prepare(tmp_path, _registry([entry]))
    with pytest.raises(sync.RegistryError, match="self-reference"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_supersession_cycle_is_rejected(tmp_path: Path) -> None:
    first = _entry("docs/a.md")
    first["supersedes"] = ["docs/b.md"]
    second = _entry("docs/b.md")
    second["title"] = "B"
    second["supersedes"] = ["docs/a.md"]
    registry_path, _ = _prepare(tmp_path, _registry([first, second]))
    with pytest.raises(sync.RegistryError, match="supersession cycle"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_symlinked_generated_output_is_rejected_without_clobber(tmp_path: Path) -> None:
    _prepare(tmp_path)
    output_path = tmp_path / sync.DEFAULT_OUTPUT
    victim = tmp_path / "victim.md"
    victim.write_text("keep me\n", encoding="utf-8")
    try:
        output_path.symlink_to(victim)
    except OSError as exc:
        pytest.skip(f"symlink creation unavailable: {exc}")
    assert sync.main(["--repo-root", str(tmp_path), "--write"]) == 2
    assert victim.read_text(encoding="utf-8") == "keep me\n"


@pytest.mark.parametrize(
    "path",
    [
        "docs/research/data/RADAR_TOPICS.json",
        "docs/research/obsidian/RESEARCH_HOME.md",
        "docs/development/research_radar/KEYWORD_MAP.md",
    ],
)
def test_radar_owned_paths_are_rejected_from_global_registry(tmp_path: Path, path: str) -> None:
    registry_path, _ = _prepare(tmp_path, _registry([_entry(path)]))
    with pytest.raises(sync.RegistryError, match="Research Radar-owned"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_authority_claim_field_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["source_of_truth"] = True
    registry_path, _ = _prepare(tmp_path, _registry([entry]))
    with pytest.raises(sync.RegistryError, match="unapproved metadata keys"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


@pytest.mark.parametrize("field", ["title", "summary"])
@pytest.mark.parametrize("value", ["line one\nline two", "line one\rline two"])
def test_multiline_rendered_string_is_rejected(tmp_path: Path, field: str, value: str) -> None:
    entry = _entry()
    entry[field] = value
    registry_path, _ = _prepare(tmp_path, _registry([entry]))
    with pytest.raises(sync.RegistryError, match="line breaks are forbidden"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_unknown_entry_key_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["made_up_field"] = "x"
    registry_path, _ = _prepare(tmp_path, _registry([entry]))
    with pytest.raises(sync.RegistryError, match="unapproved metadata keys"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_unknown_root_key_is_rejected(tmp_path: Path) -> None:
    data = _registry()
    data["source_priority"] = ["docs/doc.md"]
    registry_path, _ = _prepare(tmp_path, data)
    with pytest.raises(sync.RegistryError, match="unapproved registry root keys"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_registry_cannot_register_generated_index_or_itself(tmp_path: Path) -> None:
    for path in (sync.REGISTRY_SELF_PATH, sync.GENERATED_INDEX_PATH):
        registry_path, _ = _prepare(tmp_path, _registry([_entry(path)]))
        with pytest.raises(sync.RegistryError, match="cannot register itself"):
            sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_repository_obsidian_projections_are_current() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    ok, message = sync.check_all(repo_root)
    assert ok, message
