from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path

import pytest

from tools import obsidian_knowledge_sync as sync


def _write(path: Path, text: str = "# fixture\n") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _entry(path: str = "docs/doc.md") -> dict[str, object]:
    return {
        "path": path,
        "title": "Документ",
        "doc_type": "guide",
        "area": "project",
        "status": "active",
        "summary": "Проверочный документ.",
        "tags": ["область/project", "тип/guide", "статус/active"],
    }


def _registry(entries: list[dict[str, object]] | None = None) -> dict[str, object]:
    return {
        "schema": sync.SCHEMA,
        "schema_version": 1,
        "authority_scope": sync.AUTHORITY_SCOPE,
        "generation_direction": sync.GENERATION_DIRECTION,
        "entries": entries or [_entry()],
    }


def _prepare(tmp_path: Path, data: dict[str, object] | None = None) -> tuple[Path, Path]:
    registry_data = data or _registry()
    for raw_entry in registry_data["entries"]:  # type: ignore[index]
        entry = raw_entry  # runtime shape is a dict in all tests
        path = str(entry["path"])
        if ".." not in Path(path).parts and not path.startswith("/"):
            _write(tmp_path / path)
        for relation in sync.RELATION_KEYS:
            for target in entry.get(relation, []):  # type: ignore[union-attr]
                _write(tmp_path / str(target))
    registry_path = tmp_path / sync.DEFAULT_REGISTRY
    registry_path.parent.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(json.dumps(registry_data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return registry_path, tmp_path / sync.DEFAULT_OUTPUT


def test_write_then_check_roundtrip(tmp_path: Path) -> None:
    _, output_path = _prepare(tmp_path)

    assert sync.main(["--repo-root", str(tmp_path), "--write"]) == 0
    assert output_path.is_file()
    assert sync.main(["--repo-root", str(tmp_path), "--check"]) == 0

    text = output_path.read_text(encoding="utf-8")
    assert "GENERATED BY tools/obsidian_knowledge_sync.py" in text
    assert "knowledge_navigation_metadata_only" in text
    assert "JSON_TO_MARKDOWN" in text


def test_build_is_deterministic(tmp_path: Path) -> None:
    registry_path, _ = _prepare(tmp_path)
    _, entries_a, rendered_a = sync.build(tmp_path, registry_path)
    _, entries_b, rendered_b = sync.build(tmp_path, registry_path)
    assert entries_a == entries_b
    assert rendered_a == rendered_b


def test_check_rejects_missing_index(tmp_path: Path) -> None:
    _prepare(tmp_path)
    assert sync.main(["--repo-root", str(tmp_path), "--check"]) == 1


def test_check_rejects_stale_index(tmp_path: Path) -> None:
    _, output_path = _prepare(tmp_path)
    assert sync.main(["--repo-root", str(tmp_path), "--write"]) == 0
    output_path.write_text(output_path.read_text(encoding="utf-8") + "manual drift\n", encoding="utf-8")
    assert sync.main(["--repo-root", str(tmp_path), "--check"]) == 1


def test_invalid_vocabulary_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["doc_type"] = "unknown"
    registry_path, _ = _prepare(tmp_path, _registry([entry]))

    with pytest.raises(sync.RegistryError, match="unsupported value"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_unapproved_tag_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["tags"] = ["область/project", "тип/guide", "статус/active", "random/tag"]
    registry_path, _ = _prepare(tmp_path, _registry([entry]))

    with pytest.raises(sync.RegistryError, match="controlled taxonomy mismatch"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_missing_path_is_rejected(tmp_path: Path) -> None:
    registry_path, _ = _prepare(tmp_path, _registry([_entry("docs/missing.md")]))
    (tmp_path / "docs/missing.md").unlink()

    with pytest.raises(sync.RegistryError, match="does not exist"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_duplicate_path_is_rejected(tmp_path: Path) -> None:
    first = _entry()
    second = deepcopy(first)
    second["title"] = "Дубликат"
    registry_path, _ = _prepare(tmp_path, _registry([first, second]))

    with pytest.raises(sync.RegistryError, match="duplicate registry path"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_path_traversal_is_rejected(tmp_path: Path) -> None:
    registry_path, _ = _prepare(tmp_path, _registry([_entry("../escape.md")]))

    with pytest.raises(sync.RegistryError, match="path traversal"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_empty_optional_list_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["terms"] = []
    registry_path, _ = _prepare(tmp_path, _registry([entry]))

    with pytest.raises(sync.RegistryError, match="non-empty list"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_missing_relation_target_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["related"] = ["docs/missing-target.md"]
    registry_path, _ = _prepare(tmp_path, _registry([entry]))
    (tmp_path / "docs/missing-target.md").unlink()

    with pytest.raises(sync.RegistryError, match="referenced file does not exist"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


@pytest.mark.parametrize("bad_target", ["docs/a\nb.md", "docs/a\rb.md"])
def test_multiline_relation_target_is_rejected(tmp_path: Path, bad_target: str) -> None:
    entry = _entry()
    entry["related"] = [bad_target]
    _write(tmp_path / "docs/doc.md")
    registry_path = tmp_path / sync.DEFAULT_REGISTRY
    registry_path.parent.mkdir(parents=True, exist_ok=True)
    registry_path.write_text(
        json.dumps(_registry([entry]), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    with pytest.raises(sync.RegistryError, match="CR/LF forbidden"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_self_relation_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["related"] = ["docs/doc.md"]
    registry_path, _ = _prepare(tmp_path, _registry([entry]))

    with pytest.raises(sync.RegistryError, match="self-reference"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_supersession_cycle_is_rejected(tmp_path: Path) -> None:
    first = _entry("docs/a.md")
    first["supersedes"] = ["docs/b.md"]
    second = _entry("docs/b.md")
    second["title"] = "B"
    second["supersedes"] = ["docs/a.md"]
    registry_path, _ = _prepare(tmp_path, _registry([first, second]))

    with pytest.raises(sync.RegistryError, match="supersession cycle"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_symlinked_generated_output_is_rejected_without_clobber(tmp_path: Path) -> None:
    _, output_path = _prepare(tmp_path)
    victim = tmp_path / "victim.md"
    victim.write_text("keep me\n", encoding="utf-8")
    try:
        output_path.symlink_to(victim)
    except OSError as exc:
        pytest.skip(f"symlink creation unavailable: {exc}")

    assert sync.main(["--repo-root", str(tmp_path), "--write"]) == 2
    assert victim.read_text(encoding="utf-8") == "keep me\n"


@pytest.mark.parametrize(
    "path",
    [
        "docs/research/data/RADAR_TOPICS.json",
        "docs/research/obsidian/RESEARCH_HOME.md",
        "docs/development/research_radar/KEYWORD_MAP.md",
    ],
)
def test_radar_owned_paths_are_rejected(tmp_path: Path, path: str) -> None:
    registry_path, _ = _prepare(tmp_path, _registry([_entry(path)]))

    with pytest.raises(sync.RegistryError, match="Research Radar-owned"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_authority_claim_field_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["source_of_truth"] = True
    registry_path, _ = _prepare(tmp_path, _registry([entry]))

    with pytest.raises(sync.RegistryError, match="unapproved metadata keys"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


@pytest.mark.parametrize("field", ["title", "summary"])
@pytest.mark.parametrize("value", ["line one\nline two", "line one\rline two"])
def test_multiline_rendered_string_is_rejected(tmp_path: Path, field: str, value: str) -> None:
    entry = _entry()
    entry[field] = value
    registry_path, _ = _prepare(tmp_path, _registry([entry]))

    with pytest.raises(sync.RegistryError, match="line breaks are forbidden"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_unknown_entry_key_is_rejected(tmp_path: Path) -> None:
    entry = _entry()
    entry["made_up_field"] = "x"
    registry_path, _ = _prepare(tmp_path, _registry([entry]))

    with pytest.raises(sync.RegistryError, match="unapproved metadata keys"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_unknown_root_key_is_rejected(tmp_path: Path) -> None:
    data = _registry()
    data["source_priority"] = ["docs/doc.md"]
    registry_path, _ = _prepare(tmp_path, data)

    with pytest.raises(sync.RegistryError, match="unapproved registry root keys"):
        sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_registry_cannot_register_generated_index_or_itself(tmp_path: Path) -> None:
    for path in (sync.REGISTRY_SELF_PATH, sync.GENERATED_INDEX_PATH):
        registry_path, _ = _prepare(tmp_path, _registry([_entry(path)]))
        with pytest.raises(sync.RegistryError, match="cannot register itself"):
            sync.validate_registry(sync.load_registry(registry_path), tmp_path)


def test_repository_registry_and_generated_index_are_current() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    registry_path = repo_root / sync.DEFAULT_REGISTRY
    output_path = repo_root / sync.DEFAULT_OUTPUT
    ok, message = sync.check_index(repo_root, registry_path, output_path)
    assert ok, message
