from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MARKER = "<!-- GENERATED BY tools/research_radar_sync.py -->"
MANUAL_START = "<!-- MANUAL-NOTES-START -->"
MANUAL_END = "<!-- MANUAL-NOTES-END -->"
MANUAL_PLACEHOLDER = "<!-- Add Obsidian-only notes here. Preserved by sync. -->"
ID_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


class RadarError(RuntimeError):
    pass


def _json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RadarError(f"invalid JSON {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise RadarError(f"top-level JSON must be an object: {path}")
    return value


def load_state(root: Path = ROOT) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    data = root / "docs" / "research" / "data"
    return (
        _json(data / "RADAR_TOPICS.json"),
        _json(data / "SOURCE_REGISTRY.json"),
        _json(data / "RESEARCH_STATE.json"),
    )


def _ids(items: list[dict[str, Any]], label: str) -> set[str]:
    seen: set[str] = set()
    for item in items:
        item_id = item.get("id")
        if not isinstance(item_id, str) or not ID_RE.fullmatch(item_id):
            raise RadarError(f"{label} has invalid id: {item_id!r}")
        if item_id in seen:
            raise RadarError(f"{label} has duplicate id: {item_id}")
        seen.add(item_id)
    return seen


def validate_state(
    topics_doc: dict[str, Any],
    sources_doc: dict[str, Any],
    state_doc: dict[str, Any],
    root: Path = ROOT,
) -> None:
    for name, doc in (
        ("RADAR_TOPICS", topics_doc),
        ("SOURCE_REGISTRY", sources_doc),
        ("RESEARCH_STATE", state_doc),
    ):
        if doc.get("schema_version") != 1 or doc.get("authority") != "canonical_machine_state":
            raise RadarError(
                f"{name} must use schema_version=1 and canonical_machine_state authority"
            )

    topics = topics_doc.get("topics")
    sources = sources_doc.get("entries")
    if not isinstance(topics, list) or not all(isinstance(x, dict) for x in topics):
        raise RadarError("RADAR_TOPICS.topics must be object list")
    if not isinstance(sources, list) or not all(isinstance(x, dict) for x in sources):
        raise RadarError("SOURCE_REGISTRY.entries must be object list")

    topic_ids = _ids(topics, "topic")
    source_ids = _ids(sources, "source")

    for topic in topics:
        if topic.get("status") not in {"ACTIVE", "PAUSED"}:
            raise RadarError(f"topic {topic['id']} has unsupported status")
        for field in ("keywords", "exclusions"):
            if not isinstance(topic.get(field), list) or not all(
                isinstance(v, str) and v.strip() for v in topic[field]
            ):
                raise RadarError(
                    f"topic {topic['id']} field {field} must be a string list"
                )

    for source in sources:
        refs = source.get("topics")
        if not isinstance(refs, list) or not refs:
            raise RadarError(f"source {source['id']} needs topic refs")
        unknown = sorted(set(refs) - topic_ids)
        if unknown:
            raise RadarError(f"source {source['id']} has unknown topics: {unknown}")

        canonical = source.get("canonical_path")
        if not isinstance(canonical, str) or not canonical.strip():
            raise RadarError(
                f"source {source['id']} canonical_path is invalid: {canonical!r}"
            )
        canonical_path = Path(canonical)
        if canonical_path.is_absolute() or ".." in canonical_path.parts:
            raise RadarError(
                f"source {source['id']} canonical_path must stay repository-relative: "
                f"{canonical}"
            )
        target = (root / canonical_path).resolve()
        try:
            target.relative_to(root.resolve())
        except ValueError as exc:
            raise RadarError(
                f"source {source['id']} canonical_path escapes repository: {canonical}"
            ) from exc
        if not target.is_file():
            raise RadarError(
                f"source {source['id']} canonical_path missing: {canonical}"
            )

    seq = state_doc.get("run_sequence")
    if not isinstance(seq, int) or isinstance(seq, bool) or seq < 0:
        raise RadarError("RESEARCH_STATE.run_sequence must be non-negative int")

    known = state_doc.get("known_source_ids")
    if (
        not isinstance(known, list)
        or len(known) != len(set(known))
        or set(known) != source_ids
    ):
        raise RadarError(
            "RESEARCH_STATE.known_source_ids must match the source registry exactly"
        )

    topic_state = state_doc.get("topic_state")
    if not isinstance(topic_state, dict) or set(topic_state) != topic_ids:
        raise RadarError("RESEARCH_STATE.topic_state must cover every topic exactly")
    for topic_id, value in topic_state.items():
        if not isinstance(value, dict) or value.get("status") not in {
            "NOT_RUN",
            "CURRENT",
            "RETEST_REQUIRED",
            "PAUSED",
        }:
            raise RadarError(f"topic state {topic_id} has unsupported status")

    for field in ("suppressed_candidates", "follow_up"):
        if not isinstance(state_doc.get(field), list):
            raise RadarError(f"RESEARCH_STATE.{field} must be a list")


def extract_manual_notes(existing: str | None) -> str:
    if not existing:
        return "\n\n"
    start_count = existing.count(MANUAL_START)
    end_count = existing.count(MANUAL_END)
    if start_count == 0 and end_count == 0:
        return "\n\n"
    if start_count != 1 or end_count != 1:
        raise RadarError("manual-notes markers must occur exactly once as one pair")
    start = existing.find(MANUAL_START)
    end = existing.find(MANUAL_END)
    if end < start:
        raise RadarError("manual-notes markers are out of order")
    return existing[start + len(MANUAL_START) : end]


def _real_manual_notes(notes: str) -> bool:
    stripped = notes.strip()
    return bool(stripped and stripped != MANUAL_PLACEHOLDER)


def _manual(existing: str | None) -> str:
    notes = extract_manual_notes(existing)
    if not notes.strip():
        notes = f"\n\n{MANUAL_PLACEHOLDER}\n\n"
    return f"{MANUAL_START}{notes}{MANUAL_END}"


def _fm(**fields: Any) -> str:
    lines = ["---"]
    for key, value in fields.items():
        if isinstance(value, list):
            lines.append(f"{key}:")
            lines.extend(f"  - {json.dumps(v, ensure_ascii=False)}" for v in value)
        elif value is None:
            lines.append(f"{key}: null")
        elif isinstance(value, bool):
            lines.append(f"{key}: {'true' if value else 'false'}")
        elif isinstance(value, int):
            lines.append(f"{key}: {value}")
        else:
            lines.append(f"{key}: {json.dumps(value, ensure_ascii=False)}")
    lines += ["---", "", MARKER, ""]
    return "\n".join(lines)


def _old(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None


def _projection_input(new_path: Path, legacy_path: Path | None = None) -> str | None:
    current = _old(new_path)
    if current is not None:
        return current
    if legacy_path is not None:
        return _old(legacy_path)
    return None


def _topic_filename(item_id: str) -> str:
    return f"topic__{item_id}.md"


def _source_filename(item_id: str) -> str:
    return f"source__{item_id}.md"


def _topic_link(item: dict[str, Any]) -> str:
    return f"[[TOPICS/topic__{item['id']}|{item['title']}]]"


def _source_link(item: dict[str, Any]) -> str:
    return f"[[SOURCES/source__{item['id']}|{item['title']}]]"


def projection_plan(root: Path = ROOT) -> tuple[dict[Path, str], dict[Path, Path]]:
    topics_doc, sources_doc, state = load_state(root)
    validate_state(topics_doc, sources_doc, state, root)

    topics = topics_doc["topics"]
    sources = sources_doc["entries"]
    topic_by_id = {x["id"]: x for x in topics}
    obs = root / "docs" / "research" / "obsidian"
    legacy = root / "docs" / "development" / "research_radar"
    out: dict[Path, str] = {}
    migrations: dict[Path, Path] = {}

    home = obs / "RESEARCH_HOME.md"
    old_home = obs / "HOME.md"
    migrations[old_home] = home
    body = [
        _fm(
            id="research-home",
            type="research_home",
            generated=True,
            canonical_owner="docs/research/data",
            generation_direction="JSON_TO_MARKDOWN",
            run_sequence=state["run_sequence"],
        ),
        "# Research Radar",
        "",
        "Vault root: repository root `Genre_test/`.",
        "",
        "This subtree is the generated Research-domain projection. "
        "Canonical process rules live in `docs/research/*.md`; mutable Radar "
        "state lives in `docs/research/data/*.json`.",
        "",
        "A future project-wide Obsidian control plane under `docs/obsidian/` "
        "may link here but must not duplicate mutable Radar state.",
        "",
        "## Topics",
        "",
    ]
    body += [f"- {_topic_link(t)} — `{t['status']}`" for t in topics]
    body += ["", "## Sources / registries", ""] + [
        f"- {_source_link(s)} — `{s['kind']}` / `{s['status']}`" for s in sources
    ]
    body += [
        "",
        "## State",
        "",
        "- [[RESEARCH_STATE|Research State]]",
        "",
        "## Notes",
        "",
        _manual(_projection_input(home, old_home)),
    ]
    out[home] = "\n".join(body) + "\n"

    state_path = obs / "RESEARCH_STATE.md"
    old_state_path = obs / "STATE.md"
    migrations[old_state_path] = state_path
    body = [
        _fm(
            id="research-state",
            type="research_state",
            generated=True,
            canonical_owner="docs/research/data/RESEARCH_STATE.json",
            generation_direction="JSON_TO_MARKDOWN",
            run_sequence=state["run_sequence"],
            last_run=state["last_run"],
            last_successful_run=state["last_successful_run"],
        ),
        "# Research State",
        "",
        "This is a generated view. Edit canonical mutable state in "
        "`docs/research/data/RESEARCH_STATE.json`, not here.",
        "",
        f"- Run sequence: `{state['run_sequence']}`",
        f"- Last run: `{state['last_run']}`",
        f"- Last successful run: `{state['last_successful_run']}`",
        "",
        "## Topic state",
        "",
    ]
    for topic in topics:
        item = state["topic_state"][topic["id"]]
        body.append(
            f"- {_topic_link(topic)}: `{item['status']}`; "
            f"last checked `{item['last_checked']}`"
        )
    body += ["", "## Notes", "", _manual(_projection_input(state_path, old_state_path))]
    out[state_path] = "\n".join(body) + "\n"

    for topic in topics:
        path = obs / "TOPICS" / _topic_filename(topic["id"])
        old_path = obs / "TOPICS" / f"{topic['id']}.md"
        migrations[old_path] = path
        linked = [s for s in sources if topic["id"] in s["topics"]]
        body = [
            _fm(
                id=f"topic__{topic['id']}",
                canonical_id=topic["id"],
                type="research_topic",
                generated=True,
                canonical_owner="docs/research/data/RADAR_TOPICS.json",
                generation_direction="JSON_TO_MARKDOWN",
                status=topic["status"],
                keywords=topic["keywords"],
                exclusions=topic["exclusions"],
            ),
            f"# {topic['title']}",
            "",
            "Generated from `docs/research/data/RADAR_TOPICS.json`.",
            "",
            "## Linked sources / registries",
            "",
        ]
        body += [f"- {_source_link(s)}" for s in linked] or ["- _None registered._"]
        body += ["", "## Notes", "", _manual(_projection_input(path, old_path))]
        out[path] = "\n".join(body) + "\n"

    for source in sources:
        path = obs / "SOURCES" / _source_filename(source["id"])
        old_path = obs / "SOURCES" / f"{source['id']}.md"
        migrations[old_path] = path
        rel = Path(
            os.path.relpath(root / source["canonical_path"], start=path.parent)
        ).as_posix()
        body = [
            _fm(
                id=f"source__{source['id']}",
                canonical_id=source["id"],
                type="research_source",
                generated=True,
                canonical_owner="docs/research/data/SOURCE_REGISTRY.json",
                generation_direction="JSON_TO_MARKDOWN",
                source_kind=source["kind"],
                status=source["status"],
                canonical_path=source["canonical_path"],
                topics=source["topics"],
            ),
            f"# {source['title']}",
            "",
            "Generated from `docs/research/data/SOURCE_REGISTRY.json`.",
            "",
            f"[Open canonical artifact]({rel})",
            "",
            "## Topics",
            "",
        ]
        body += [f"- {_topic_link(topic_by_id[t])}" for t in source["topics"]]
        body += ["", "## Notes", "", _manual(_projection_input(path, old_path))]
        out[path] = "\n".join(body) + "\n"

    header = MARKER + "\n\n"
    out[legacy / "README.md"] = header + (
        "# Research Radar compatibility entrypoint\n\n"
        "This directory is a generated compatibility facade. Canonical load order:\n\n"
        "1. `../../research/RESEARCH_OPERATING_RULES.md`\n"
        "2. `../../research/RESEARCH_RADAR.md`\n"
        "3. `../../research/data/RADAR_TOPICS.json`\n"
        "4. `../../research/data/SOURCE_REGISTRY.json`\n"
        "5. `../../research/data/RESEARCH_STATE.json`\n\n"
        "These Markdown files are not independent state. Regenerate with "
        "`python tools/research_radar_sync.py`.\n"
    )
    out[legacy / "RESEARCH_PROMPT.md"] = header + (
        "# Research Prompt compatibility bootstrap\n\n"
        "Do not use remembered chat instructions as source of truth. At every run "
        "fetch current `main`, then read `AGENTS.md`, "
        "`docs/research/RESEARCH_OPERATING_RULES.md`, "
        "`docs/research/RESEARCH_RADAR.md`, the three canonical JSON files under "
        "`docs/research/data/`, referenced specialized registries, and recent "
        "relevant run evidence. Then execute the current Radar procedure completely.\n\n"
        "This compatibility file is not an independent copy of the research policy.\n"
    )
    lines = [
        header + "# Keyword Map (generated view)",
        "",
        "Canonical research keyword/topic semantics live in `../../research/data/RADAR_TOPICS.json`.",
        "",
        "| Topic | Status | Keywords | Exclusions |",
        "|---|---|---|---|",
    ]
    for t in topics:
        lines.append(
            f"| `{t['id']}` | `{t['status']}` | {', '.join(t['keywords'])} | "
            f"{', '.join(t['exclusions'])} |"
        )
    out[legacy / "KEYWORD_MAP.md"] = "\n".join(lines) + "\n"

    lines = [
        header + "# Source Registry (generated view)",
        "",
        "| ID | Kind | Status | Topics | Canonical artifact |",
        "|---|---|---|---|---|",
    ]
    for s in sources:
        lines.append(
            f"| `{s['id']}` | `{s['kind']}` | `{s['status']}` | "
            f"{', '.join(s['topics'])} | `{s['canonical_path']}` |"
        )
    out[legacy / "SOURCE_REGISTRY.md"] = "\n".join(lines) + "\n"

    lines = [
        header + "# Research State (generated view)",
        "",
        f"- Run sequence: `{state['run_sequence']}`",
        f"- Last run: `{state['last_run']}`",
        f"- Last successful run: `{state['last_successful_run']}`",
        f"- Known source IDs: `{len(state['known_source_ids'])}`",
        "",
        "## Topic state",
        "",
    ]
    for t in topics:
        item = state["topic_state"][t["id"]]
        lines.append(
            f"- `{t['id']}`: `{item['status']}`; "
            f"last checked `{item['last_checked']}`"
        )
    lines += ["", "Canonical state: `../../research/data/RESEARCH_STATE.json`."]
    out[legacy / "RESEARCH_STATE.md"] = "\n".join(lines) + "\n"
    out[legacy / "runs" / "README.md"] = header + (
        "# Research runs compatibility view\n\n"
        "Canonical concise run records live under `../../../research/runs/`. "
        "Do not store raw search dumps here.\n"
    )
    return out, migrations


def expected_projection(root: Path = ROOT) -> dict[Path, str]:
    expected, _ = projection_plan(root)
    return expected


def _stale_generated_files(expected: set[Path], root: Path) -> list[Path]:
    bases = (
        root / "docs" / "research" / "obsidian",
        root / "docs" / "development" / "research_radar",
    )
    stale: list[Path] = []
    for base in bases:
        if not base.exists():
            continue
        for path in base.rglob("*.md"):
            if path in expected:
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except OSError as exc:
                raise RadarError(f"cannot read generated projection {path}: {exc}") from exc
            if MARKER in text:
                stale.append(path)
    return sorted(stale)


def _preflight_stale(stale: list[Path], migrations: dict[Path, Path]) -> None:
    for path in stale:
        text = path.read_text(encoding="utf-8")
        notes = extract_manual_notes(text)
        target = migrations.get(path)
        if target is not None:
            if not _real_manual_notes(notes):
                continue
            target_text = _old(target)
            if target_text is None:
                continue
            if extract_manual_notes(target_text) == notes:
                continue
            raise RadarError(
                "refusing to remove renamed generated page because its manual notes "
                f"are not preserved in target: {path}"
            )
        if _real_manual_notes(notes):
            raise RadarError(
                "refusing to remove stale generated page with manual notes: "
                f"{path}"
            )


def sync(root: Path = ROOT, check: bool = False) -> int:
    expected, migrations = projection_plan(root)
    stale = _stale_generated_files(set(expected), root)
    _preflight_stale(stale, migrations)

    drift: list[str] = []
    for path, content in expected.items():
        if _old(path) != content:
            drift.append(str(path.relative_to(root)))
    drift += [str(path.relative_to(root)) for path in stale]

    if check:
        if drift:
            for item in sorted(set(drift)):
                print(f"Research Radar projection drift: {item}", file=sys.stderr)
            return 1
        return 0

    for path, content in expected.items():
        if _old(path) == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    for path in stale:
        path.unlink()
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sync Research Radar JSON to Markdown/Obsidian projections"
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        return sync(check=args.check)
    except RadarError as exc:
        print(f"Research Radar error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
